pypyr-ops 7.0.0

diff --git a/pypyr-go/Dockerfile b/pypyr-go/Dockerfile
--- a/pypyr-go/Dockerfile
+++ b/pypyr-go/Dockerfile
@@ -7,7 +7,7 @@
 # docker build -t pypyr/pypyr-go -t pypyr/pypyr-go:latest -t pypyr/pypyr-go:1.10 -t pypyr/pypyr-go:1.10.3 -f pypyr-go/Dockerfile .
 FROM pypyr/pypyr:5.9.1
 
-ARG goversion=1.15.7
+ARG goversion=1.21.4
 # username for limited user from base image
 ARG limiteduser=pypyruser
 
@@ -31,58 +31,67 @@ ENV PATH /usr/local/go/bin:$PATH
 ENV GOLANG_VERSION=${goversion}
 
 RUN set -eux; \
-	\
-	dpkgArch="$(dpkg --print-architecture)"; \
-	case "${dpkgArch##*-}" in \
+	arch="$(dpkg --print-architecture)"; arch="${arch##*-}"; \
+	url=; \
+	case "$arch" in \
 	'amd64') \
-	arch='linux-amd64'; \
-	url='https://storage.googleapis.com/golang/go1.15.7.linux-amd64.tar.gz'; \
-	sha256='0d142143794721bb63ce6c8a6180c4062bcf8ef4715e7d6d6609f3a8282629b3'; \
+	url='https://dl.google.com/go/go1.21.4.linux-amd64.tar.gz'; \
+	sha256='73cac0215254d0c7d1241fa40837851f3b9a8a742d0b54714cbdfb3feaf8f0af'; \
+	;; \
+	'armel') \
+	export GOARCH='arm' GOARM='5' GOOS='linux'; \
 	;; \
 	'armhf') \
-	arch='linux-armv6l'; \
-	url='https://storage.googleapis.com/golang/go1.15.7.linux-armv6l.tar.gz'; \
-	sha256='8ab192799a191eb3752079ab17efff12d1d7dd0e965cf84dcbf08d55542e27d3'; \
+	url='https://dl.google.com/go/go1.21.4.linux-armv6l.tar.gz'; \
+	sha256='6c62e89113750cc77c498194d13a03fadfda22bd2c7d44e8a826fd354db60252'; \
 	;; \
 	'arm64') \
-	arch='linux-arm64'; \
-	url='https://storage.googleapis.com/golang/go1.15.7.linux-arm64.tar.gz'; \
-	sha256='bca4af0c20f86521dfabf3b39fa2f1ceeeb11cebf7e90bdf1de2618c40628539'; \
+	url='https://dl.google.com/go/go1.21.4.linux-arm64.tar.gz'; \
+	sha256='ce1983a7289856c3a918e1fd26d41e072cc39f928adfb11ba1896440849b95da'; \
 	;; \
 	'i386') \
-	arch='linux-386'; \
-	url='https://storage.googleapis.com/golang/go1.15.7.linux-386.tar.gz'; \
-	sha256='519e5d7518376bc6b87afc04f16e72db66d9bc08641d9b4385ecf1f30e55e64c'; \
+	url='https://dl.google.com/go/go1.21.4.linux-386.tar.gz'; \
+	sha256='64d3e5d295806e137c9e39d1e1f10b00a30fcd5c2f230d72b3298f579bb3c89a'; \
+	;; \
+	'mips64el') \
+	url='https://dl.google.com/go/go1.21.4.linux-mips64le.tar.gz'; \
+	sha256='c7ce3a9dcf03322b79beda474c4a0154393d9029b48f7c2e260fb3365c8a6ad3'; \
 	;; \
 	'ppc64el') \
-	arch='linux-ppc64le'; \
-	url='https://storage.googleapis.com/golang/go1.15.7.linux-ppc64le.tar.gz'; \
-	sha256='665bbd512dcc83f15e0d48140f687e3dedf5103c363599ef910a5328894bf039'; \
+	url='https://dl.google.com/go/go1.21.4.linux-ppc64le.tar.gz'; \
+	sha256='2c63b36d2adcfb22013102a2ee730f058ec2f93b9f27479793c80b2e3641783f'; \
+	;; \
+	'riscv64') \
+	url='https://dl.google.com/go/go1.21.4.linux-riscv64.tar.gz'; \
+	sha256='9695edd2109544b364daddb32816f5c7980f1f48b8490c51fa2c167f5b2eca48'; \
 	;; \
 	's390x') \
-	arch='linux-s390x'; \
-	url='https://storage.googleapis.com/golang/go1.15.7.linux-s390x.tar.gz'; \
-	sha256='d15867ee945cb7b18a627a4eb55e2ee1fb7bf04c138ed8bb741a5f727c35819f'; \
+	url='https://dl.google.com/go/go1.21.4.linux-s390x.tar.gz'; \
+	sha256='7a75ba4afc7a96058ca65903d994cd862381825d7dca12b2183f087c757c26c0'; \
 	;; \
-	*) \
-	# https://github.com/golang/go/issues/38536#issuecomment-616897960
-	arch='src'; \
-	url='https://storage.googleapis.com/golang/go1.15.7.src.tar.gz'; \
-	sha256='8631b3aafd8ecb9244ec2ffb8a2a8b4983cf4ad15572b9801f7c5b167c1a2abc'; \
-	echo >&2; \
-	echo >&2 "warning: current architecture ($dpkgArch) does not have a corresponding Go binary release; will be building from source"; \
-	echo >&2; \
-	;; \
+	*) echo >&2 "error: unsupported architecture '$arch' (likely packaging update needed)"; exit 1 ;; \
 	esac; \
+	build=; \
+	if [ -z "$url" ]; then \
+	# https://github.com/golang/go/issues/38536#issuecomment-616897960
+	build=1; \
+	url='https://dl.google.com/go/go1.21.4.src.tar.gz'; \
+	sha256='47b26a83d2b65a3c1c1bcace273b69bee49a7a7b5168a7604ded3d26a37bd787'; \
+	echo >&2; \
+	echo >&2 "warning: current architecture ($arch) does not have a compatible Go binary release; will be building from source"; \
+	echo >&2; \
+	fi; \
 	\
-	wget -O go.tgz.asc "$url.asc" --progress=dot:giga; \
+	wget -O go.tgz.asc "$url.asc"; \
 	wget -O go.tgz "$url" --progress=dot:giga; \
-	echo "$sha256 *go.tgz" | sha256sum --strict --check -; \
+	echo "$sha256 *go.tgz" | sha256sum -c -; \
 	\
 	# https://github.com/golang/go/issues/14739#issuecomment-324767697
-	export GNUPGHOME="$(mktemp -d)"; \
+	GNUPGHOME="$(mktemp -d)"; export GNUPGHOME; \
 	# https://www.google.com/linuxrepositories/
-	gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys 'EB4C 1BFD 4F04 2F6D DDCC EC91 7721 F63B D38B 4796'; \
+	gpg --batch --keyserver keyserver.ubuntu.com --recv-keys 'EB4C 1BFD 4F04 2F6D DDCC  EC91 7721 F63B D38B 4796'; \
+	# let's also fetch the specific subkey of that key explicitly that we expect "go.tgz.asc" to be signed by, just to make sure we definitely have it
+	gpg --batch --keyserver keyserver.ubuntu.com --recv-keys '2F52 8D36 D67B 69ED F998  D857 78BD 6547 3CB3 BD13'; \
 	gpg --batch --verify go.tgz.asc go.tgz; \
 	gpgconf --kill all; \
 	rm -rf "$GNUPGHOME" go.tgz.asc; \
@@ -90,17 +99,17 @@ RUN set -eux; \
 	tar -C /usr/local -xzf go.tgz; \
 	rm go.tgz; \
 	\
-	if [ "$arch" = 'src' ]; then \
+	if [ -n "$build" ]; then \
 	savedAptMark="$(apt-mark showmanual)"; \
 	apt-get update; \
 	apt-get install -y --no-install-recommends golang-go; \
 	\
-	goEnv="$(go env | sed -rn -e '/^GO(OS|ARCH|ARM|386)=/s//export \0/p')"; \
-	eval "$goEnv"; \
-	[ -n "$GOOS" ]; \
-	[ -n "$GOARCH" ]; \
+	export GOCACHE='/tmp/gocache'; \
+	\
 	( \
 	cd /usr/local/go/src; \
+	# set GOROOT_BOOTSTRAP + GOHOST* such that we can build Go successfully
+	export GOROOT_BOOTSTRAP="$(go env GOROOT)" GOHOSTOS="$GOOS" GOHOSTARCH="$GOARCH"; \
 	./make.bash; \
 	); \
 	\
@@ -108,11 +117,6 @@ RUN set -eux; \
 	apt-mark manual $savedAptMark > /dev/null; \
 	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
 	rm -rf /var/lib/apt/lists/*; \
-	\
-	# pre-compile the standard library, just like the official binary release tarballs do
-	go install std; \
-	# go install: -race is only supported on linux/amd64, linux/ppc64le, linux/arm64, freebsd/amd64, netbsd/amd64, darwin/amd64 and windows/amd64
-	#		go install -race std; \
 	\
 	# remove a few intermediate / bootstrapping files the official binary release tarballs do not contain
 	rm -rf \
@@ -122,10 +126,15 @@ RUN set -eux; \
 	/usr/local/go/pkg/tool/*/api \
 	/usr/local/go/pkg/tool/*/go_bootstrap \
 	/usr/local/go/src/cmd/dist/dist \
+	"$GOCACHE" \
 	; \
 	fi; \
 	\
 	go version
+
+# don't auto-upgrade the gotoolchain
+# https://github.com/docker-library/golang/issues/472
+ENV GOTOOLCHAIN=local
 
 ENV GOPATH /go
 ENV PATH $GOPATH/bin:$PATH
